INSERT INTO EQUIPMENT_TYPE (EQUIPMENT_TYPE_KEY, DESCRIPTION ,NAME ) VALUES (2, 'EQUIPOS DE CONSTRUCCION', 'CONSTRUCCION');
INSERT INTO EQUIPMENT_TYPE (EQUIPMENT_TYPE_KEY, DESCRIPTION ,NAME ) VALUES (2, 'EQUIPOS DE SEGURIDAD', 'SEGURIDAD');
INSERT INTO EQUIPMENT_TYPE (EQUIPMENT_TYPE_KEY, DESCRIPTION ,NAME ) VALUES (3, 'DISPOSITIVOS DE COMUNICACION', 'COMUNICACION');

INSERT INTO EQUIPMENT (EQUIPMENT_KEY ,CODE ,DESCRIPTION ,EQUIPMENT_INSERT INTO ORGANIZATION (ORGANIZATION_KEY ,CREATED_ON ,UPDATED_ON ,VERSION ,CODE ,DESCRIPTION, END ,GESTION ,HIERARCHICAL_LEVEL_KEY ,ID_PADRE ,NAME ,START, STATUS ) VALUES  (1, '2018-03-04', '2018-04-28', 1, '2002', 'BUILDER', '2018-01-01', '2018', '7', '6', 'EMPLOYEE', '2018-12-01' ,1);TYPE_KEY ,NAME ,STATUS ) VALUES (1, '1002', 'GUANTES ANTIESTATICOS', 1, 'GUANTES', 1);



